base_images:
  cli:
    name: "4.16"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-8-release-golang-1.22-openshift-4.17
images:
- context_dir: .
  dockerfile_path: Dockerfile
  to: distributed-tracing-tests-runner
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.16"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: distributed-tracing-tests-dast
  cluster_claim:
    architecture: amd64
    cloud: aws
    labels:
      region: us-east-2
    owner: obs-tracing
    product: ocp
    timeout: 1h0m0s
    version: "4.16"
  steps:
    env:
      OPERATORS: |
        [
         {"name": "ptp-operator", "source": "redhat-operators", "channel": "stable", "install_namespace": "openshift-ptp","target_namespaces": "openshift-ptp", "operator_group": "ptp-operators"},
         {"name": "numaresources-operator", "source": "redhat-operators", "channel": "4.16", "install_namespace": "openshift-numaresources","target_namespaces": "openshift-numaresources", "operator_group": "numaresources-operator"}
        ]
    test:
    - ref: enable-stage-catalogsource
    - ref: install-operators
    - ref: distributed-tracing-tests-dast
    workflow: generic-claim
zz_generated_metadata:
  branch: main
  org: openshift
  repo: distributed-tracing-qe
  variant: ocp-4.16-Telco-dast
